---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: my-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector: 
    matchLabels:
      app: mypodlabel
  template:
    metadata:
      name: my-pod
      labels:
        app: mypodlabel
    spec:
      containers:
        - image: prajwreddy/myimagecicdprj
          name: my-container
          ports:
            containerPort: 8501
...
---
kind: Service
apiVersion: v1
metadata: 
  name: my-service
spec:
  type: NodePort
  selector:
    app: mypodlabel
  ports:
    - port: 80
    targetPort: 8501
    nodePort: 300001
...
